# Prometheus version: 2.29.1
# Node Exporter version: 1.2.2
# Alertmanager version: 0.23.0

# Global configuration for Prometheus server
global:
  # Defines how frequently Prometheus will scrape targets
  scrape_interval: 15s
  # Defines how frequently Prometheus will evaluate rules
  evaluation_interval: 15s
  # External labels to identify this Prometheus instance
  external_labels:
    environment: production
    region: us-east-1

# Rule files for recording and alerting rules
rule_files:
  - /etc/prometheus/rules/recording.rules
  - /etc/prometheus/rules/alerting.rules

# Scrape configurations for monitoring various services
scrape_configs:
  # Kubernetes services monitoring configuration
  - job_name: kubernetes-services
    kubernetes_sd_configs:
      - role: service
        namespaces:
          names: 
            - default
            - monitoring
    # Relabeling configurations to filter and modify labels
    relabel_configs:
      # Keep only services with specific app labels
      - source_labels: [__meta_kubernetes_service_label_app]
        action: keep
        regex: backend|frontend|ocr
      # Keep only services with prometheus.io/scrape annotation set to true
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        action: keep
        regex: true
    # Drop unnecessary Go runtime metrics to reduce storage usage
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: go_.*
        action: drop

  # Node metrics monitoring configuration
  - job_name: node-metrics
    static_configs:
      - targets: ['localhost:9100']
    metrics_path: /metrics
    scheme: http

  # API endpoints monitoring configuration
  - job_name: api-endpoints
    metrics_path: /metrics
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      # Keep only endpoints with prometheus.io/scrape annotation
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      # Use custom metrics path if specified in annotations
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)

  # Rate limits monitoring configuration
  - job_name: rate-limits
    metrics_path: /metrics/rate-limits
    static_configs:
      - targets: ['api-gateway:8080']
    scrape_interval: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
      scheme: http
      timeout: 10s
      api_version: v2

# Storage configuration for time series data
storage:
  tsdb:
    # Retention configuration for metrics data
    retention_time: 15d
    retention_size: 50GB